mongo-url = "mongodb://data-platform-mongodb-replicaset-kube:27017"

change-stream-namespaces = [""]

elasticsearch-urls = ["http://data-platform-elasticsearch-kube:9200"]

elasticsearch-max-conns = 1

elasticsearch-max-seconds = 1

elasticsearch-max-docs = 1

verbose = true

enable-http-server = true
